# Generated by Django 3.2 on 2021-09-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='detial',
            new_name='detail',
        ),
    ]
